apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-go-cobra-app.fullname" . }}
  labels:
    {{- include "template-go-cobra-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "template-go-cobra-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "template-go-cobra-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "template-go-cobra-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: ENABLE_HEALTH_CHECK
              value: {{ .Values.healthCheck.enabled | quote }}
            - name: HEALTH_CHECK_PATH
              value: {{ .Values.healthCheck.path }}
            - name: HEALTH_CHECK_PORT
              value: {{ .Values.healthCheck.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: health
              containerPort: {{ .Values.healthCheck.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{ .Values.healthCheck.port }}
              path: {{ .Values.healthCheck.path }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
