{{- if .Values.imagePullSecretCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret-credentials
data:
  .dockerconfigjson: {{ .Values.imagePullSecretCredentials }}
type: kubernetes.io/dockerconfigjson
{{- end }}