name: Validate PR
on:
  pull_request:
    branches:
      - main
      - alpha
    paths:
      - 'chart/**'
jobs:
  conventional-commits-pr:
    if: github.event.pull_request.draft == false
    name: Validate Conventional Commits PR
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: catalystsquad/action-validate-conventional-commits-pr@v1
  validate-chart:
    if: ${{ !startsWith( github.head_ref, 'automated-code-release' ) }}
    name: Validate Chart
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: catalystsquad/action-validate-helm-chart@v1